<Project Sdk="Dalamud.NET.Sdk/15.0.0">

  <PropertyGroup>
    <Version>0.1.0.0</Version>
    <Description>Automatise le rangement des tenues dans la coiffeuse. Experimental.</Description>
    <PackageProjectUrl>https://github.com/Olympia-Guardian/codex-olympia-dalamud</PackageProjectUrl>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
